openapi: 3.0.0
info:
  title: Update Beneficiary Details API
  version: 1.0.0
paths:
  /update-beneficiary-details:
    post:
      summary: Update beneficiary details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestID:
                  type: string
                  minLength: 12
                  maxLength: 12
                SourceBBID:
                  type: string
                  minLength: 12
                  maxLength: 12
                Beneficiaries:
                  type: array
                  items:
                    type: object
                    properties:
                      PayeeFunctionalID:
                        type: string
                        minLength: 20
                        maxLength: 20
                      PaymentModality:
                        type: string
                        minLength: 2
                        maxLength: 2
                      FinancialAddress:
                        type: string
                        maxLength: 30
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseCode:
                    type: string
                    minLength: 2
                    maxLength: 2
                  ResponseDescription:
                    type: string
                    maxLength: 200
                  RequestID:
                    type: string
                    minLength: 12
                    maxLength: 12
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseCode:
                    type: string
                    minLength: 2
                    maxLength: 2
                  ResponseDescription:
                    type: string
                    maxLength: 200
                  RequestID:
                    type: string
                    minLength: 12
                    maxLength: 12
